### ISSUE TITLE
关于websocket报错

### ISSUE THREAD

**Issue by zhanglonglongSH** [AlayaNetwork/client-sdk-python#2]
#!/usr/bin/env python
# _*_ coding: utf-8 _*_
# @Time : 2021/7/19 5:48 下午
# @Author : zhanglonglogn
# @Version：V 0.1
# @desc
from client_sdk_python import Web3, HTTPProvider, WebsocketProvider
from client_sdk_python.eth import PlatON

w3 = Web3(WebsocketProvider("ws://47.241.91.2:6790"),chain_id = 100)
alaya = PlatON(w3)
print(w3.isConnected())

/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/bin/python3.9 /Users/longlongzhanq/spider_product/Platon_alaya/test.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/main.py", line 134, in __init__
    self.net_type = self.getAddressHrp
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/main.py", line 237, in getAddressHrp
    return self.manager.request_blocking("platon_getAddressHrp", [])
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/manager.py", line 92, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/providers/websocket.py", line 119, in make_request
    return future.result()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/providers/websocket.py", line 100, in coro_make_request
    await asyncio.wait_for(
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/websockets/protocol.py", line 371, in send
    yield from self.write_frame(opcode, data)
  File "/usr/local/lib/python3.9/site-packages/websockets/protocol.py", line 740, in write_frame
    with (yield from self._drain_lock):
TypeError: 'Lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/longlongzhanq/spider_product/Platon_alaya/test.py", line 10, in <module>
    w3 = Web3(WebsocketProvider("ws://47.241.91.2:6790"),chain_id = 100)
  File "/usr/local/lib/python3.9/site-packages/client_sdk_python/main.py", line 137, in __init__
    raise ValueError(
ValueError: Failed to obtain hrp automatically,need to be passed in from outside,exception info:'Lock' object is not iterable

**Comment by sigrlot** [comment]
hi， 这是websockets版本较低引发的问题，pip install websockets==8.0.0  可以解决该问题。

**Comment by zhanglonglongSH** [comment]
client-sdk-python 1.0.0 requires websockets<7.0.0,&gt;=6.0.0, but you have websockets 8.0 which is incompatible.



client-sdk-python 里面设置的websockets 版本为 websockets<7.0.0,&gt;=6.0.0 ，建议优化


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlayaNetwork/client-sdk-python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 下午5:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlayaNetwork/client-sdk-python] 关于websocket报错 (#2)





 
hi， 这是websockets版本较低引发的问题，pip install websockets==8.0.0  可以解决该问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
