### ISSUE TITLE
合约问题

### ISSUE THREAD

**Issue by zhanglonglongSH** [AlayaNetwork/client-sdk-python#6]
源码：  
         from client_sdk_python import HTTPProvider, Web3, WebsocketProvider
              from client_sdk_python.eth import PlatON
              from hexbytes import HexBytes
              from client_sdk_python import Web3, HTTPProvider
              from client_sdk_python.eth import PlatON
              true = True
              false = False
              
              
              w3 = Web3(HTTPProvider("http://47.241.91.2:6789"),chain_id = 201030)
              # alaya为PlatON类的一个实例
              alaya = PlatON(w3)
              print(w3.isConnected())
              from_address = "atp1gljs4x28mrxkguf58h68aqlgcfa66zsgctu3tl"
              
              bytecode = '0x608060405234801561001057600080fd5b50610429806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806317d7de7c1461003b578063c47f0027146100be575b600080fd5b6100436101f2565b6040518080602001828103825283818151815260200191508051906020019080838360005b83811015610083578082015181840152602081019050610068565b50505050905090810190601f1680156100b05780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b610177600480360360208110156100d457600080fd5b81019080803590602001906401000000008111156100f157600080fd5b82018360208201111561010357600080fd5b8035906020019184600183028401116401000000008311171561012557600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610294565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156101b757808201518184015260208101905061019c565b50505050905090810190601f1680156101e45780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b606060008054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561028a5780601f1061025f5761010080835404028352916020019161028a565b820191906000526020600020905b81548152906001019060200180831161026d57829003601f168201915b5050505050905090565b606081600090805190602001906102ac92919061034f565b5060008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156103435780601f1061031857610100808354040283529160200191610343565b820191906000526020600020905b81548152906001019060200180831161032657829003601f168201915b50505050509050919050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061039057805160ff19168380011785556103be565b828001600101855582156103be579182015b828111156103bd5782518255916020019190600101906103a2565b5b5090506103cb91906103cf565b5090565b6103f191905b808211156103ed5760008160009055506001016103d5565b5090565b9056fea265627a7a72315820c704da051789dd93ae9c3d1c876c282314bd25861550841a9f97522f8f064a4f64736f6c63430005110032'
              
              abi = [{"constant": false,"inputs": [{"internalType": "string","name": "_name","type": "string"}],"name": "setName","outputs": [{"internalType": "string","name": "","type": "string"}],"payable": false,"stateMutability": "nonpayable","type": "function"},{"constant": true,"inputs": [],"name": "getName","outputs": [{"internalType": "string","name": "","type": "string"}],"payable": false,"stateMutability": "view","type": "function"}]
              
              def contract_deploy(bytecode, fromAddress):
                  bytecode = bytecode
                  transactionHash = alaya.sendTransaction(
                      {
                          "from": fromAddress,
                          "gas": 1000000,
                          "gasPrice": 1000000000,
                          "data": bytecode,
                      }
                  )
                  transactionHash = HexBytes(transactionHash).hex().lower()
                  return transactionHash
              
              tx = contract_deploy(bytecode, from_address)
              print(tx)
              tx_receipt = alaya.waitForTransactionReceipt(tx)
              print(tx_receipt)
              contractAddress = tx_receipt.contractAddress
              print(contractAddress)

一直报：ValueError: {'code': -32000, 'message': 'unknown account'}

 address地址 是我开发网的地址。  当前使用的sdk版本：1.0.0.2 。  abi，bytecode是我运行测试网Helloworld合约编译出来的  
麻烦问一下那块出现问题了 ，并且目前本地合约部署 到开发网络一直报
Error: The network id specified in the truffle config (201030) does not match the one returned by the network (1).  Ensure that both the network and the provider are properly configured.
    at Object.detectAndSetNetworkId (/usr/local/lib/node_modules/platon-truffle/build/webpack:/packages/environment/environment.js:97:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v1.0.0 (core: 1.0.0)
Node v10.15.3

**Comment by biganxin** [comment]
看错误原因，未知账户？是不是因为这个原因--开放的开发网节点没有开放Personal接口，无法直接上述命令，需要使用本地私钥直接签名的命令?

具体 @shinnng @lyc-huc 支持下

**Comment by sigrlot** [comment]
你的交易是发往本地节点，但是目标节点上并不存在from_address的钱包文件。
如果你确实要这么做，那么你需要在节点侧放置你的钱包文件，并且unlock。  
或者，你可以在sdk用私钥直接签名你的交易，这样就可以任意发送了。

**Comment by biganxin** [comment]
建议优化文档说明
